# Generated by Django 5.2.3 on 2025-11-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='voting_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='voting_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='voting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
