# Generated by Django 5.2.3 on 2026-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminuser_voting_active_adminuser_voting_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='voting_active',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='voting_duration',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='voting_started_at',
        ),
        migrations.AddField(
            model_name='votingtime',
            name='voting_active',
            field=models.BooleanField(default=False),
        ),
    ]
